"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { storeWalletSeed } from "@/lib/wallet-vault";
type WalletResult = { address: string; seed: string; balanceXrp: string };
export default function OnboardingPage() {
  const [accountType, setAccountType] = useState<"buyer" | "provider">("buyer"); const [walletPassword, setWalletPassword] = useState(""); const [result, setResult] = useState<WalletResult | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { createClient().then(client => client.auth.getUser()).then(({ data }) => { if (!data.user) location.assign("/auth"); }).catch(error => setMessage(error instanceof Error ? error.message : "Configuration unavailable.")); }, []);
  async function createWallet(event: React.FormEvent) { event.preventDefault(); setMessage(""); if (walletPassword.length < 10) return setMessage("Use at least 10 characters to encrypt the wallet on this device."); const response = await fetch("/api/wallets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ accountType }) }); const payload = await response.json(); if (!response.ok) return setMessage(payload.error || "Wallet creation failed."); await storeWalletSeed(payload.address, payload.seed, walletPassword); setResult(payload); }
  if (result) return <main className="shell"><section className="details"><div className="eyebrow">XRPL TESTNET WALLET CREATED</div><h1 style={{ fontSize: 42 }}>Save your recovery seed now.</h1><p className="notice"><strong>Address:</strong> {result.address}<br/><strong>Recovery seed:</strong> {result.seed}</p><p className="lead">The seed is encrypted only in this browser with the wallet password you chose. Proofly cannot recover it. Store it offline before continuing.</p><a className="button" href={accountType === "provider" ? "/offer" : "/"}>I saved my seed</a></section></main>;
  return <main className="shell"><nav className="nav"><a className="brand" href="/">proof<i>ly</i></a></nav><section className="details"><div className="eyebrow">STEP 2 OF 2</div><h1 style={{ fontSize: 48 }}>Create your Testnet wallet</h1><p className="lead">Choose how you want to use Proofly. Provider applications are hidden until a real-person review is approved.</p><form className="profile" onSubmit={createWallet} noValidate><label><input type="radio" checked={accountType === "buyer"} onChange={() => setAccountType("buyer")}/> I want to purchase services</label><br/><label><input type="radio" checked={accountType === "provider"} onChange={() => setAccountType("provider")}/> I want to offer services</label><label style={{ display: "block", marginTop: 20 }}>Wallet password (at least 10 characters; local encryption only)<br/><input required type="password" value={walletPassword} onChange={event => setWalletPassword(event.target.value)} style={{ width: "100%", padding: 12, margin: "8px 0 16px" }}/></label><button className="button">Create funded XRP Testnet wallet</button>{message && <p className="notice">{message}</p>}</form></section></main>;
}
