import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function ProviderProfile({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const supabase = await createClient();
  const { data: service } = await supabase.from("services").select("id,slug,title,description,category,price_cents,provider:providers!inner(id,bio,verification_status,profile:profiles(display_name))").eq("slug", slug).eq("is_active", true).eq("provider.verification_status", "approved").single();
  if (!service) notFound(); const provider = Array.isArray(service.provider) ? service.provider[0] : service.provider; const profile = Array.isArray(provider?.profile) ? provider?.profile[0] : provider?.profile;
  const { data: reviews } = await supabase.from("reviews").select("rating,body,created_at,blockchain_mint_transaction_hash,author:profiles(display_name)").eq("provider_id", provider.id).order("created_at", { ascending: false });
  return <main className="shell"><nav className="nav"><Link className="brand" href="/">proof<i>ly</i></Link><Link className="button secondary" href="/auth">Sign in</Link></nav><section className="details"><Link href="/" className="back">← Back to search</Link><div className="profile"><div className="eyebrow">{service.category}</div><h1 style={{ fontSize: 48 }}>{profile?.display_name}</h1><p className="rating">€{(service.price_cents / 100).toFixed(2)}/hour</p><div className="verify">✓ Identity review approved &nbsp; ✓ XRP payment required &nbsp; ✓ On-chain rating tokens</div><p className="lead" style={{ fontSize: 17 }}>{service.description}</p><Link className="button" href={`/book/${service.slug}`}>Book this service</Link><div className="notice"><strong>What “Verified Service” means</strong><br/>A review is linked to a completed booking, an XRP Testnet payment, and a customer-minted XRPL NFT rating token. Personal details and the review body are never put on-chain.</div><h2>Reviews</h2>{reviews?.length ? reviews.map((review) => { const author = Array.isArray(review.author) ? review.author[0] : review.author; return <article className="review" key={review.blockchain_mint_transaction_hash}><strong>{author?.display_name || "Verified customer"} · {"★".repeat(review.rating)}</strong><p>{review.body}</p><div className="verify">✓ Verified service · <a href={`https://testnet.xrpl.org/transactions/${review.blockchain_mint_transaction_hash}`} target="_blank" rel="noreferrer">View rating token on XRPL</a></div></article>; }) : <p className="muted">No verified reviews yet.</p>}</div></section></main>;
}
