"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function OfferPage() {
  const [message, setMessage] = useState(""); const [ready, setReady] = useState(false);
  useEffect(() => { createClient().then(client => client.auth.getUser()).then(({ data }) => { if (!data.user) location.assign("/auth"); else setReady(true); }).catch(error => setMessage(error instanceof Error ? error.message : "Configuration unavailable.")); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/providers/apply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, priceCents: Math.round(Number(values.price) * 100) }) }); const result = await response.json(); setMessage(response.ok ? "Your service is pending manual identity review. It cannot be discovered or booked until approved." : result.error || "Application failed."); }
  if (!ready) return <main className="shell"><section className="details"><p className="lead">Checking your secure session…</p></section></main>;
  return <main className="shell"><nav className="nav"><a className="brand" href="/">proof<i>ly</i></a></nav><section className="details"><div className="eyebrow">PROVIDER APPLICATION</div><h1 style={{ fontSize: 44 }}>Apply to offer a real service</h1><p className="lead">You need a confirmed email and a Proofly provider wallet. Applications stay private until identity review is approved.</p><form className="profile" onSubmit={submit}><label>Service title<br/><input name="title" required minLength={3} style={{ width: "100%", padding: 10, margin: "8px 0 16px" }}/></label><label>Category<br/><input name="category" required minLength={3} style={{ width: "100%", padding: 10, margin: "8px 0 16px" }}/></label><label>Description<br/><textarea name="description" required minLength={30} style={{ width: "100%", padding: 10, margin: "8px 0 16px" }}/></label><label>About you<br/><textarea name="bio" required minLength={30} style={{ width: "100%", padding: 10, margin: "8px 0 16px" }}/></label><label>Price per hour (€)<br/><input name="price" type="number" min="1" max="10000" step="0.01" required style={{ width: "100%", padding: 10, margin: "8px 0 16px" }}/></label><button className="button">Submit for review</button>{message && <p className="notice">{message}</p>}</form></section></main>;
}
