"use client";
import { useEffect, useState } from "react";
import { Client, Wallet } from "xrpl";
import { createClient } from "@/lib/supabase/client";
import { loadWalletSeed } from "@/lib/wallet-vault";

type Booking = { id: string; status: string; total_cents: number; service: { title: string } | { title: string }[] | null };
type Proof = { id: string; booking_id: string; review_used_at: string | null };

export default function AccountPage() {
  const [bookings, setBookings] = useState<Booking[]>([]); const [proofs, setProofs] = useState<Proof[]>([]); const [address, setAddress] = useState(""); const [proofId, setProofId] = useState(""); const [rating, setRating] = useState(5); const [body, setBody] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  async function refresh() { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return location.assign("/auth"); const [{ data: bookingRows }, { data: proofRows }, { data: profile }] = await Promise.all([supabase.from("bookings").select("id,status,total_cents,service:services(title)").order("created_at", { ascending: false }), supabase.from("proofs_of_service").select("id,booking_id,review_used_at"), supabase.from("profiles").select("wallet_address").eq("id", user.id).single()]); setBookings((bookingRows || []) as Booking[]); setProofs((proofRows || []) as Proof[]); setAddress(profile?.wallet_address || ""); }
  useEffect(() => { refresh(); }, []);
  async function complete(id: string) { const response = await fetch(`/api/bookings/${id}/complete`, { method: "POST" }); const data = await response.json(); setMessage(response.ok ? (data.proof ? "Both parties confirmed. You can now mint a rating token." : "Completion recorded. Waiting for the other party to confirm.") : data.error); await refresh(); }
  async function mintAndPublish(event: React.FormEvent) { event.preventDefault(); try { setMessage("Preparing the on-chain rating token…"); const intentResponse = await fetch("/api/reviews/intent", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ proofId, rating }) }); const intent = await intentResponse.json(); if (!intentResponse.ok) throw new Error(intent.error); const seed = await loadWalletSeed(address, password); const wallet = Wallet.fromSeed(seed); const client = new Client("wss://s.altnet.rippletest.net:51233"); await client.connect(); const prepared = await client.autofill(intent.transaction); const signed = wallet.sign(prepared).tx_blob; await client.disconnect(); const submitResponse = await fetch("/api/xrpl/submit", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ signedTransaction: signed }) }); const submitted = await submitResponse.json(); if (!submitResponse.ok) throw new Error(submitted.error); const reviewResponse = await fetch("/api/reviews", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ proofId, rating, body, blockchainMintTransactionHash: submitted.hash }) }); const review = await reviewResponse.json(); if (!reviewResponse.ok) throw new Error(review.error); setMessage(`Rating published and token validated: https://testnet.xrpl.org/transactions/${submitted.hash}`); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Rating publication failed"); } }
  return <main className="shell"><nav className="nav"><a className="brand" href="/">proof<i>ly</i></a></nav><section className="details"><div className="eyebrow">YOUR PROOFLY ACCOUNT</div><h1 style={{ fontSize: 44 }}>Bookings & XRPL proof</h1><p className="lead">Wallet: {address || "Create your wallet in onboarding"}</p><h2>Bookings</h2>{bookings.length ? bookings.map((booking) => { const service = Array.isArray(booking.service) ? booking.service[0] : booking.service; return <article className="review" key={booking.id}><strong>{service?.title || "Service"}</strong><p>Status: {booking.status} · €{(booking.total_cents / 100).toFixed(2)}</p>{booking.status === "paid" && <button className="button secondary" onClick={() => complete(booking.id)}>Confirm completion</button>}</article>; }) : <p className="muted">No bookings yet.</p>}<h2>Publish a verified rating</h2><form className="profile" onSubmit={mintAndPublish}><label>Completed proof<br/><select required value={proofId} onChange={event => setProofId(event.target.value)} style={{ width: "100%", padding: 10, margin: "8px 0 16px" }}><option value="">Choose a completed service</option>{proofs.filter(proof => !proof.review_used_at).map(proof => <option value={proof.id} key={proof.id}>{proof.booking_id}</option>)}</select></label><label>Rating<br/><select value={rating} onChange={event => setRating(Number(event.target.value))} style={{ width: "100%", padding: 10, margin: "8px 0 16px"}}>{[5,4,3,2,1].map(value => <option value={value} key={value}>{value} stars</option>)}</select></label><label>Review<br/><textarea required minLength={3} maxLength={2000} value={body} onChange={event => setBody(event.target.value)} style={{ width: "100%", padding: 10, margin: "8px 0 16px"}}/></label><label>Wallet password<br/><input required type="password" value={password} onChange={event => setPassword(event.target.value)} style={{ width: "100%", padding: 10, margin: "8px 0 16px"}}/></label><button className="button">Mint XRPL rating token & publish review</button></form>{message && <p className="notice">{message}</p>}</section></main>;
}
