"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import { Client, Wallet } from "xrpl";
import { loadWalletSeed } from "@/lib/wallet-vault";

export default function BookingPage(){const [result,setResult]=useState("");const [bookingId,setBookingId]=useState("");const [walletPassword,setWalletPassword]=useState("");const params=useParams<{slug:string}>(); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,slug:params.slug})});const payload=await response.json();if(response.ok){setBookingId(payload.booking.id);setResult(`Booking created. Pay it now with your Proofly Testnet wallet.`);}else setResult(payload.error||"Could not create booking. Please sign in and create a wallet first.");}
  async function pay(){try{setResult("Preparing your XRP Testnet payment…");const intentResponse=await fetch("/api/payments/intent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingId})});const intent=await intentResponse.json();if(!intentResponse.ok)throw new Error(intent.error);const seed=await loadWalletSeed(intent.transaction.Account,walletPassword);const wallet=Wallet.fromSeed(seed);const client=new Client("wss://s.altnet.rippletest.net:51233");await client.connect();const prepared=await client.autofill(intent.transaction);const signed=wallet.sign(prepared).tx_blob;await client.disconnect();const submitted=await fetch("/api/xrpl/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signedTransaction:signed})});const submittedBody=await submitted.json();if(!submitted.ok)throw new Error(submittedBody.error);const verified=await fetch("/api/payments/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingId,transactionHash:submittedBody.hash})});const verifiedBody=await verified.json();if(!verified.ok)throw new Error(verifiedBody.error);setResult(`Payment validated on XRPL. View it: https://testnet.xrpl.org/transactions/${submittedBody.hash}`);}catch(error){setResult(error instanceof Error?error.message:"Payment failed");}}
  return <main className="shell"><nav className="nav"><a className="brand" href="/">proof<i>ly</i></a></nav><section className="details"><h1 style={{fontSize:48}}>Book service</h1><p className="lead">The final price is paid in XRP Testnet drops and independently verified against the XRPL ledger.</p><form className="profile" onSubmit={submit}><label>Date<br/><input name="scheduled_for" type="datetime-local" required style={{margin:"8px 0 16px",padding:10,width:"100%"}}/></label><label>Hours<br/><input name="hours" type="number" min="1" max="8" defaultValue="2" required style={{margin:"8px 0 16px",padding:10,width:"100%"}}/></label><button className="button">Confirm booking</button></form>{bookingId&&<div className="notice"><label>Wallet password<br/><input type="password" value={walletPassword} onChange={event=>setWalletPassword(event.target.value)} style={{margin:"8px 0 12px",padding:10,width:"100%"}}/></label><button className="button" onClick={pay}>Pay with XRP Testnet</button></div>}{result&&<p className="notice">{result}</p>}</section></main>}
